### PR TITLE
Add ignores/dirty so the branch stays clean/_more_ pullable in prod

### PR DESCRIPTION
**Pull request by khandieyea**
This is mainly focused on 1.1 (our current production env), but easily repeatable for v1.2

Once the repo has been pulled, deps installed and config is done, we're left with a pretty dirty branch making it challenging to bring in new changes/updates.

I've moved ispConfig.py, shaper.csv, and network.json files to *.examples instead, and the of names are ignored from git. 
To use this approach, simply `cp ispConfig.example.py ispConfig.py` etc and you're away.

With the git submodules, adding `ignore = dirty` tells git not to care if any submodules repos are dirty, which most are after build.

### CODE REVIEW

**Comment by interduo** [comment]
very good approach - could You apply the same for v1.2?

**Comment by khandieyea** [comment]
Yea absolutely, just coming up to speed with 1.2. I'll add changes to this
PR

**Comment by interduo** [comment]
btw bump up Your version of LibreQoS, reloading time drops to nearly or nerly above 80% ;-)

**Comment by khandieyea** [comment]
Will do 🍻

**Pull request merged**
